#!/usr/bin/env python3
"""
PhotoVerify — Safe Photo Backup Verification Tool
──────────────────────────────────────────────────
Run:  python3 photo_verify.py
Then: open http://localhost:7734 (opens automatically)

SAFETY GUARANTEE:
  • Source folder      → read-only, never modified
  • Destination folder → read-only, never modified
  • Only output folders (missing / review) are written to

Matching strategy (in order):
  1. Filename match     (fast, case-insensitive)
  2. EXIF datetime+size (handles renamed files)
  3. MD5 hash           (on-demand, for confirmed missing)

Author: generated by Claude
"""

import os, sys, json, hashlib, shutil, threading, time, webbrowser, io, struct, logging
from datetime import datetime
from pathlib import Path
from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs, unquote

# ─── Dependency bootstrap ────────────────────────────────────────────────────

def _pip_install(pkg):
    import subprocess
    print(f"  Installing {pkg}...")
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", pkg, "--quiet"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )

try:
    from PIL import Image, ExifTags
    PIL_OK = True
except ImportError:
    try:
        _pip_install("Pillow")
        from PIL import Image, ExifTags
        PIL_OK = True
    except Exception as e:
        PIL_OK = False
        print(f"  Warning: Pillow unavailable ({e}). Thumbnails and EXIF matching disabled.")

try:
    import yaml
    YAML_OK = True
except ImportError:
    try:
        _pip_install("pyyaml")
        import yaml
        YAML_OK = True
    except Exception as e:
        YAML_OK = False
        print(f"  Warning: PyYAML unavailable ({e}). Config persistence disabled.")

# ─── Configuration ────────────────────────────────────────────────────────────

PORT        = 7734
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
CACHE_DIR   = os.path.join(BASE_DIR, "cache")
LOGS_DIR    = os.path.join(BASE_DIR, "logs")
CONFIG_DIR  = os.path.join(BASE_DIR, "config")
MISSING_DIR = os.path.join(BASE_DIR, "missing")
REVIEW_DIR  = os.path.join(BASE_DIR, "review")
THUMB_SIZE = 320   # px
THUMB_CACHE_MAX = 800  # entries kept in memory

PHOTO_EXT = {
    '.jpg', '.jpeg', '.png', '.heic', '.heif',
    '.raw', '.dng', '.cr2', '.nef', '.arw',
    '.tiff', '.tif', '.bmp', '.webp', '.gif',
    '.orf', '.rw2', '.pef', '.srw', '.x3f',
}

# ─── Global App State ─────────────────────────────────────────────────────────

_state = {
    'cfg': {
        'src':         '',
        'dest':        '',
        'missing_dir': '',
        'review_dir':  '',
        'move_mode':   False,   # False = copy, True = move
    },
    'src_photos': [],           # sorted list of absolute paths
    'dest_idx': {
        'fname': {},            # lowercase_basename → [path, ...]
        'exif':  {},            # "YYYY:MM:DD HH:MM:SS|size" → [path, ...]
        'hash':  {},            # md5hex → path  (built lazily)
    },
    'idx_status': {
        'phase':   'idle',      # idle | scanning | building | done | error
        'current': 0,
        'total':   0,
        'msg':     'Not started.',
    },
    'action_log': [],
    'progress':    {},          # src_path → 'found'|'missing'|'review'
    'active_cache': '',         # path to the currently-active cache file
    'last_idx':     0,          # last viewed photo index, persisted to cache
    'session_ts':   '',         # timestamp subfolder for output files this session
    '_thumb_cache':  {},        # path → jpeg_bytes  (LRU-ish)
    '_thumb_order':  [],        # insertion order for eviction
    '_state_lock':   threading.Lock(),
}

# ─── Cache helpers ───────────────────────────────────────────────────────────

def _new_cache_path() -> str:
    os.makedirs(CACHE_DIR, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return os.path.join(CACHE_DIR, f"{stamp}_photoverify_cache.json")

def list_cache_files() -> list:
    """Return cache entries sorted newest-first."""
    if not os.path.isdir(CACHE_DIR):
        return []
    entries = []
    for name in sorted(os.listdir(CACHE_DIR), reverse=True):
        if not name.endswith("_photoverify_cache.json"):
            continue
        full = os.path.join(CACHE_DIR, name)
        try:
            with open(full) as f:
                meta = json.load(f)
            n = sum(len(v) for v in meta.get('fname', {}).values())
            entries.append({
                'file': full,
                'name': name,
                'dest': meta.get('dest', ''),
                'ts':   meta.get('ts', 0),
                'n':    n,
            })
        except Exception:
            pass
    return entries

def _config_path() -> str:
    os.makedirs(CONFIG_DIR, exist_ok=True)
    ts = _state.get('session_ts', '') or datetime.now().strftime("%Y%m%d_%H%M%S")
    return os.path.join(CONFIG_DIR, f"{ts}_photoverify_config.yaml")

def _apply_config_dict(saved: dict):
    for k in ('src', 'dest', 'missing_dir', 'review_dir', 'move_mode'):
        if k in saved:
            _state['cfg'][k] = saved[k]

def _nearest_config_yaml(ts: str):
    """Return path to the config yaml closest in time to ts (within 5 min), or None."""
    if not os.path.isdir(CONFIG_DIR):
        return None
    try:
        cache_dt = datetime.strptime(ts, "%Y%m%d_%H%M%S")
    except ValueError:
        return None
    best_path, best_delta = None, None
    for fname in os.listdir(CONFIG_DIR):
        if not fname.endswith('_photoverify_config.yaml'):
            continue
        f_ts = '_'.join(fname.split('_')[:2])
        try:
            delta = abs((datetime.strptime(f_ts, "%Y%m%d_%H%M%S") - cache_dt).total_seconds())
            if best_delta is None or delta < best_delta:
                best_delta, best_path = delta, os.path.join(CONFIG_DIR, fname)
        except ValueError:
            continue
    return best_path if (best_delta is not None and best_delta <= 300) else None

def _load_config_for_cache(cache_path: str):
    """Load the config file whose timestamp matches the given cache file."""
    if not YAML_OK:
        return
    basename = os.path.basename(cache_path)
    ts       = '_'.join(basename.split('_')[:2])
    cfg_path = os.path.join(CONFIG_DIR, f"{ts}_photoverify_config.yaml")
    if not os.path.isfile(cfg_path):
        cfg_path = _nearest_config_yaml(ts)
    if not cfg_path:
        return
    try:
        with open(cfg_path) as f:
            _apply_config_dict(yaml.safe_load(f) or {})
    except Exception as e:
        print(f"  Config load for cache failed: {e}")

def _persist_config():
    """Write current config to config/<session_ts>_photoverify_config.yaml."""
    if not YAML_OK:
        return
    try:
        with open(_config_path(), 'w') as f:
            yaml.dump(dict(_state['cfg']), f, default_flow_style=False, allow_unicode=True)
    except Exception as e:
        print(f"  Config save failed: {e}")

def _save_progress(src_path: str, status: str):
    """Write one progress entry into the active cache file."""
    cache_file = _state.get('active_cache', '')
    if not cache_file or not os.path.isfile(cache_file):
        return
    _state['progress'][src_path] = status
    try:
        with open(cache_file) as f:
            data = json.load(f)
        data['progress'] = _state['progress']
        data['last_idx'] = _state['last_idx']
        with open(cache_file, 'w') as f:
            json.dump(data, f, separators=(',', ':'))
    except Exception as e:
        _log(f"Progress save failed: {e}")

_loggers: dict = {}  # log_path → logging.Logger

def _get_logger() -> logging.Logger:
    cache = _state.get('active_cache', '')
    base  = (os.path.splitext(os.path.basename(cache))[0] + '.log') if cache else 'photoverify.log'
    os.makedirs(LOGS_DIR, exist_ok=True)
    log_path = os.path.join(LOGS_DIR, base)
    if log_path not in _loggers:
        logger = logging.getLogger(f'photoverify.{log_path}')
        logger.setLevel(logging.DEBUG)
        handler = logging.FileHandler(log_path, encoding='utf-8')
        handler.setFormatter(logging.Formatter(
            '%(asctime)s [%(levelname)-5s] %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S',
        ))
        logger.addHandler(handler)
        _loggers[log_path] = logger
    return _loggers[log_path]

def _log(msg: str, level: int = logging.ERROR):
    try:
        _get_logger().log(level, msg)
    except Exception as e:
        print(f"  Log write failed: {e}")

# ─── Filesystem helpers ───────────────────────────────────────────────────────

def scan_photos(folder: str) -> list:
    """Recursively scan folder; return sorted list of photo paths."""
    results = []
    try:
        for root, dirs, files in os.walk(folder, followlinks=False):
            # Skip hidden dirs (e.g. .@eaDir on Synology)
            dirs[:] = [d for d in dirs if not d.startswith('.')]
            for f in files:
                if Path(f).suffix.lower() in PHOTO_EXT:
                    results.append(os.path.join(root, f))
    except PermissionError as e:
        print(f"  Permission denied: {e}")
    return sorted(results)

def get_exif_datetime(path: str):
    """Return EXIF DateTimeOriginal string or None."""
    if not PIL_OK:
        return None
    try:
        with Image.open(path) as img:
            exif = img._getexif()
            if exif:
                for tag_id, val in exif.items():
                    tag = ExifTags.TAGS.get(tag_id, '')
                    if tag in ('DateTimeOriginal', 'DateTime'):
                        return str(val).strip()
    except Exception:
        pass
    return None

def file_md5(path: str):
    """Compute MD5 hex digest of a file."""
    h = hashlib.md5()
    try:
        with open(path, 'rb') as f:
            for chunk in iter(lambda: f.read(131072), b''):
                h.update(chunk)
        return h.hexdigest()
    except Exception:
        return None

def make_thumbnail(path: str, size: int = THUMB_SIZE) -> bytes | None:
    """Render a JPEG thumbnail, honouring EXIF rotation."""
    if not PIL_OK:
        return None
    cache = _state['_thumb_cache']
    if path in cache:
        return cache[path]
    try:
        with Image.open(path) as img:
            # EXIF auto-rotate
            try:
                exif = img._getexif()
                if exif:
                    for tid, val in exif.items():
                        if ExifTags.TAGS.get(tid) == 'Orientation':
                            rot = {3: 180, 6: 270, 8: 90}
                            if val in rot:
                                img = img.rotate(rot[val], expand=True)
            except Exception:
                pass
            img.thumbnail((size, size), Image.LANCZOS)
            if img.mode not in ('RGB', 'L'):
                img = img.convert('RGB')
            buf = io.BytesIO()
            img.save(buf, 'JPEG', quality=84, optimize=True)
            data = buf.getvalue()
    except Exception:
        return None

    # Cache with simple eviction
    order = _state['_thumb_order']
    if len(order) >= THUMB_CACHE_MAX:
        oldest = order.pop(0)
        cache.pop(oldest, None)
    cache[path] = data
    order.append(path)
    return data

# ─── Indexing ─────────────────────────────────────────────────────────────────

def _index_worker():
    st  = _state['idx_status']
    cfg = _state['cfg']
    dest = cfg['dest']

    if not dest or not os.path.isdir(dest):
        st.update({'phase': 'error', 'msg': f'Destination folder not accessible: {dest}'})
        return

    # ── Phase 1: Scan ──
    st.update({'phase': 'scanning', 'current': 0, 'total': 0,
               'msg': 'Scanning destination folder...'})
    photos = scan_photos(dest)
    n = len(photos)
    st.update({'total': n, 'msg': f'Found {n} photos. Building index…'})

    # ── Phase 2: Build filename + EXIF index ──
    st['phase'] = 'building'
    fname_idx: dict = {}
    exif_idx:  dict = {}

    for i, path in enumerate(photos):
        st['current'] = i + 1

        # Filename
        fname_idx.setdefault(Path(path).name.lower(), []).append(path)

        # EXIF + size
        dt = get_exif_datetime(path)
        if dt:
            sz  = os.path.getsize(path)
            key = f"{dt}|{sz}"
            exif_idx.setdefault(key, []).append(path)

    _state['dest_idx']['fname'] = fname_idx
    _state['dest_idx']['exif']  = exif_idx

    # ── Save cache with timestamped filename ──
    try:
        cache_path = _new_cache_path()
        with open(cache_path, 'w') as f:
            json.dump({
                'src':      cfg['src'],
                'dest':     dest,
                'fname':    fname_idx,
                'exif':     exif_idx,
                'ts':       time.time(),
                'progress': {},
            }, f, separators=(',', ':'))
        st['last_cache'] = cache_path
        _state['active_cache'] = cache_path
        _state['progress'] = {}
        # Pin session_ts to the cache filename so config yaml shares the same timestamp
        _state['session_ts'] = '_'.join(os.path.basename(cache_path).split('_')[:2])
    except Exception as e:
        print(f"  Cache write failed: {e}")

    n_f = len(fname_idx)
    n_e = len(exif_idx)
    st.update({
        'phase':   'done',
        'current': n, 'total': n,
        'msg':     f'Done — {n} photos indexed '
                   f'({n_f} unique filenames, {n_e} EXIF entries).'
    })

# ─── Matching ─────────────────────────────────────────────────────────────────

def find_match(src_path: str) -> dict | None:
    """Fast match: filename → EXIF. Returns match dict or None."""
    idx = _state['dest_idx']

    # 1. Filename (case-insensitive)
    fname = Path(src_path).name.lower()
    if fname in idx['fname']:
        hits = idx['fname'][fname]
        return {'method': 'filename', 'path': hits[0], 'n': len(hits)}

    # 2. EXIF datetime + file size
    dt = get_exif_datetime(src_path)
    if dt:
        sz  = os.path.getsize(src_path)
        key = f"{dt}|{sz}"
        if key in idx['exif']:
            hits = idx['exif'][key]
            return {'method': 'exif', 'path': hits[0], 'n': len(hits)}

    return None

def deep_find(src_path: str) -> dict | None:
    """
    Hash-based match. Computes MD5 of src, then scans entire dest folder
    computing hashes on the fly (slow — only call when fast match fails).
    Results are cached to speed up subsequent calls.
    """
    src_hash = file_md5(src_path)
    if not src_hash:
        return None

    hash_idx = _state['dest_idx']['hash']

    # Check already-computed hash cache
    if src_hash in hash_idx:
        return {'method': 'hash', 'path': hash_idx[src_hash], 'n': 1}

    # Scan dest, building hash cache as we go
    dest = _state['cfg']['dest']
    for dp in scan_photos(dest):
        if dp in hash_idx.values():
            continue  # already cached this path → different hash
        dh = file_md5(dp)
        if dh:
            hash_idx[dh] = dp
            if dh == src_hash:
                return {'method': 'hash', 'path': dp, 'n': 1}

    return None

# ─── File actions ─────────────────────────────────────────────────────────────

def do_action(src_idx: int, dest_type: str) -> tuple[bool, str]:
    """
    Copy (or move) src photo → missing_dir or review_dir.
    NEVER touches the destination folder.
    Returns (ok, message).
    """
    photos = _state['src_photos']
    if not (0 <= src_idx < len(photos)):
        return False, 'Invalid photo index'

    src = photos[src_idx]
    if not os.path.exists(src):
        return False, f'Source file not found: {src}'

    folder_key = 'missing_dir' if dest_type == 'missing' else 'review_dir'
    out_dir = os.path.expanduser(_state['cfg'][folder_key] or '')
    if not out_dir:
        label = 'Missing' if dest_type == 'missing' else 'Review'
        return False, f'{label} output folder not configured'
    ts = _state.get('session_ts', '')
    if ts:
        out_dir = os.path.join(out_dir, ts)

    # Safety: refuse to write into src or dest (skip check if either is unconfigured)
    out_real = os.path.realpath(out_dir)
    for guarded in (_state['cfg']['src'], _state['cfg']['dest']):
        if not guarded:
            continue
        g = os.path.realpath(guarded)
        if out_real == g or out_real.startswith(g + os.sep):
            return False, 'Output folder must not be inside src or dest!'

    os.makedirs(out_dir, exist_ok=True)

    name = Path(src).name
    dst  = os.path.join(out_dir, name)

    # Skip if already copied/moved to this session folder
    if os.path.exists(dst):
        return True, '_skipped_'

    # Avoid collision with a differently-named file sharing the same stem
    stem, suf = Path(src).stem, Path(src).suffix
    if any(f.startswith(stem) for f in os.listdir(out_dir)):
        dst = os.path.join(out_dir, f"{stem}_{int(time.time() * 1000)}{suf}")

    try:
        if _state['cfg']['move_mode']:
            shutil.move(src, dst)
            verb = 'Moved'
        else:
            shutil.copy2(src, dst)
            verb = 'Copied'
        _state['action_log'].append({
            't':    time.time(),
            'src':  src,
            'dst':  dst,
            'type': dest_type,
            'verb': verb,
        })
        return True, dst
    except Exception as e:
        return False, str(e)

# ─── HTTP Handler ─────────────────────────────────────────────────────────────

class PhotoVerifyHandler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        pass  # Suppress default request log spam

    # ── Response helpers ──────────────────────────────────────────────────────

    def _json(self, data: dict, code: int = 200):
        body = json.dumps(data).encode()
        self.send_response(code)
        self.send_header('Content-Type',   'application/json')
        self.send_header('Content-Length', str(len(body)))
        self.send_header('Cache-Control',  'no-cache')
        self.end_headers()
        self.wfile.write(body)

    def _image(self, data: bytes, mime: str = 'image/jpeg'):
        self.send_response(200)
        self.send_header('Content-Type',   mime)
        self.send_header('Content-Length', str(len(data)))
        self.send_header('Cache-Control',  'max-age=300')
        self.end_headers()
        self.wfile.write(data)

    def _404(self):
        self.send_response(404)
        self.end_headers()

    def _read_body(self) -> dict:
        n = int(self.headers.get('Content-Length', 0))
        return json.loads(self.rfile.read(n)) if n else {}

    # ── GET ───────────────────────────────────────────────────────────────────

    def do_GET(self):
        u  = urlparse(self.path)
        qs = parse_qs(u.query)

        if u.path == '/':
            html = _HTML.encode('utf-8')
            self.send_response(200)
            self.send_header('Content-Type',   'text/html; charset=utf-8')
            self.send_header('Content-Length', str(len(html)))
            self.send_header('Cache-Control',  'no-store')
            self.end_headers()
            self.wfile.write(html)

        elif u.path == '/api/state':
            self._json({
                'cfg':          _state['cfg'],
                'src_count':    len(_state['src_photos']),
                'idx':          _state['idx_status'],
                'pil':          PIL_OK,
                'log_count':    len(_state['action_log']),
                'active_cache': _state.get('active_cache', ''),
            })

        elif u.path == '/api/list':
            page    = int(qs.get('p', ['0'])[0])
            per     = 200
            photos  = _state['src_photos']
            start   = page * per
            batch   = photos[start:start + per]
            self._json({
                'items': [{'i': start + j, 'name': Path(p).name, 'path': p}
                          for j, p in enumerate(batch)],
                'total': len(photos),
                'page':  page,
                'pages': max(1, -(-len(photos) // per)),
            })

        elif u.path == '/api/photo':
            i = int(qs.get('i', ['0'])[0])
            photos = _state['src_photos']
            if 0 <= i < len(photos):
                p = photos[i]
                dt = get_exif_datetime(p) or '—'
                self._json({
                    'idx':  i,
                    'name': Path(p).name,
                    'path': p,
                    'size': os.path.getsize(p),
                    'exif_dt': dt,
                    'total': len(photos),
                })
            else:
                self._404()

        elif u.path == '/api/match':
            i = int(qs.get('i', ['0'])[0])
            photos = _state['src_photos']
            if 0 <= i < len(photos):
                self._json({'match': find_match(photos[i])})
            else:
                self._404()

        elif u.path == '/api/deep_match':
            i = int(qs.get('i', ['0'])[0])
            photos = _state['src_photos']
            if 0 <= i < len(photos):
                m = deep_find(photos[i])
                self._json({'match': m})
            else:
                self._404()

        elif u.path == '/api/log':
            self._json({'log': _state['action_log'][-200:]})

        elif u.path == '/api/list_caches':
            self._json({'caches': list_cache_files()})

        # ── Thumbnails ────────────────────────────────────────────────────────

        elif u.path == '/thumb/src':
            i = int(qs.get('i', ['-1'])[0])
            photos = _state['src_photos']
            if 0 <= i < len(photos):
                data = make_thumbnail(photos[i])
                if data:
                    self._image(data)
                else:
                    self._404()
            else:
                self._404()

        elif u.path == '/thumb/dest':
            p = unquote(qs.get('p', [''])[0])
            if p and os.path.isfile(p):
                data = make_thumbnail(p)
                if data:
                    self._image(data)
                else:
                    self._404()
            else:
                self._404()

        else:
            self._404()

    # ── POST ──────────────────────────────────────────────────────────────────

    def do_POST(self):
        try:
            self._do_POST_inner()
        except Exception:
            import traceback
            tb = traceback.format_exc()
            _log(f"Unhandled POST error:\n{tb.rstrip()}")
            self._json({'ok': False, 'msg': tb.splitlines()[-1]}, code=500)

    def _do_POST_inner(self):
        body = self._read_body()
        u    = urlparse(self.path)

        if u.path == '/api/configure':
            cfg = body.get('cfg', {})
            for k in ('src', 'dest', 'missing_dir', 'review_dir', 'move_mode'):
                if k in cfg:
                    _state['cfg'][k] = cfg[k]
            _persist_config()
            # Backfill src into the active cache so future loads can recover it
            cache_file = _state.get('active_cache', '')
            if cache_file and os.path.isfile(cache_file) and _state['cfg'].get('src'):
                try:
                    with open(cache_file) as f:
                        cdata = json.load(f)
                    cdata['src'] = _state['cfg']['src']
                    with open(cache_file, 'w') as f:
                        json.dump(cdata, f, separators=(',', ':'))
                except Exception:
                    pass
            # Re-scan src
            src = _state['cfg']['src']
            if src:
                _state['src_photos'] = scan_photos(src) if os.path.isdir(src) else []
            self._json({'ok': True, 'src_count': len(_state['src_photos'])})

        elif u.path == '/api/start_index':
            if _state['idx_status']['phase'] in ('scanning', 'building'):
                self._json({'ok': False, 'msg': 'Already indexing — please wait.'})
                return
            if body.get('dest'):
                _state['cfg']['dest'] = body['dest']
            dest = _state['cfg'].get('dest', '')
            if not dest:
                self._json({'ok': False, 'msg': 'Set destination folder first.'})
                return
            # Reset
            _state['dest_idx'] = {'fname': {}, 'exif': {}, 'hash': {}}
            _state['idx_status'] = {
                'phase': 'starting', 'current': 0, 'total': 0, 'msg': 'Starting…'
            }
            threading.Thread(target=_index_worker, daemon=True).start()
            self._json({'ok': True})

        elif u.path == '/api/move':
            ok, result = do_action(body.get('i', -1), body.get('type', 'missing'))
            self._json({'ok': ok, 'result': result})

        elif u.path == '/api/load_cache':
            file = body.get('file', '')
            if not file or not os.path.isfile(file):
                self._json({'ok': False, 'msg': 'Cache file not found.'})
                return
            try:
                with open(file) as f:
                    cache = json.load(f)
                _state['dest_idx']['fname'] = cache['fname']
                _state['dest_idx']['exif']  = cache['exif']
                _state['dest_idx']['hash']  = {}
                _state['progress']    = cache.get('progress', {})
                _state['last_idx']    = cache.get('last_idx', 0)
                _state['active_cache'] = file
                _state['session_ts'] = '_'.join(os.path.basename(file).split('_')[:2])
                # src/dest are stored in the cache itself — always restore them
                if cache.get('src'):
                    _state['cfg']['src']  = cache['src']
                if cache.get('dest'):
                    _state['cfg']['dest'] = cache['dest']
                # missing_dir/review_dir/move_mode come from the matching config yaml
                _load_config_for_cache(file)
                n = sum(len(v) for v in cache['fname'].values())
                _state['idx_status'].update({
                    'phase': 'done', 'current': n, 'total': n,
                    'msg': f'Loaded from cache — {n} photos indexed.',
                })
                self._json({'ok': True, 'n': n,
                            'progress': _state['progress'],
                            'last_idx': _state['last_idx'],
                            'cfg': _state['cfg']})
            except Exception as e:
                self._json({'ok': False, 'msg': str(e)})

        elif u.path == '/api/save_progress_bulk':
            idx_map  = body.get('idx_map', {})
            last_idx = body.get('last_idx', 0)
            cache_file = _state.get('active_cache', '')
            if not cache_file:
                self._json({'ok': False, 'msg': 'No active cache — index or load a cache first.'})
                return
            photos = _state['src_photos']
            progress = {}
            for idx_str, status in idx_map.items():
                idx = int(idx_str)
                if 0 <= idx < len(photos) and status in ('found', 'missing', 'review'):
                    progress[photos[idx]] = status
            _state['progress'] = progress
            _state['last_idx'] = last_idx
            try:
                with open(cache_file) as f:
                    data = json.load(f)
                data['progress'] = progress
                data['last_idx'] = last_idx
                with open(cache_file, 'w') as f:
                    json.dump(data, f, separators=(',', ':'))
                self._json({'ok': True, 'saved': len(progress)})
            except Exception as e:
                _log(f"Bulk progress save failed: {e}")
                self._json({'ok': False, 'msg': str(e)})

        elif u.path == '/api/bulk_action':
            indices   = body.get('indices', [])
            dest_type = body.get('type', 'missing')
            succeeded, failed, skipped = [], [], 0
            out_folder = ''
            for idx in indices:
                ok, result = do_action(int(idx), dest_type)
                if ok:
                    succeeded.append(idx)
                    if not out_folder:
                        out_folder = os.path.dirname(result)
                elif result == '_skipped_':
                    skipped += 1
                else:
                    failed.append({'i': idx, 'msg': result})
            self._json({'ok': True, 'saved': len(succeeded),
                        'skipped': skipped, 'failed': failed,
                        'out_folder': out_folder})

        elif u.path == '/api/batch_match':
            force   = body.get('force', False)
            photos  = _state['src_photos']
            prog    = _state['progress']
            results = []
            found   = missing = skipped = 0
            for i, path in enumerate(photos):
                if not force and path in prog:
                    skipped += 1
                    results.append({'i': i, 'status': prog[path], 'method': None})
                    continue
                m = find_match(path)
                if m:
                    status = 'found'
                    found += 1
                else:
                    status = 'missing'
                    missing += 1
                prog[path] = status
                results.append({'i': i, 'status': status, 'method': m['method'] if m else None})
            _state['progress'] = prog
            cache_file = _state.get('active_cache', '')
            if cache_file and os.path.isfile(cache_file):
                try:
                    with open(cache_file) as f:
                        data = json.load(f)
                    data['progress'] = prog
                    with open(cache_file, 'w') as f:
                        json.dump(data, f, separators=(',', ':'))
                except Exception as e:
                    _log(f"Batch match cache write failed: {e}")
            self._json({'ok': True, 'results': results,
                        'found': found, 'missing': missing,
                        'skipped': skipped, 'total': len(photos)})

        elif u.path == '/api/save_position':
            idx = body.get('idx', 0)
            _state['last_idx'] = idx
            cache_file = _state.get('active_cache', '')
            if cache_file and os.path.isfile(cache_file):
                try:
                    with open(cache_file) as f:
                        data = json.load(f)
                    data['last_idx'] = idx
                    with open(cache_file, 'w') as f:
                        json.dump(data, f, separators=(',', ':'))
                except Exception as e:
                    _log(f"Position save failed: {e}")
            self._json({'ok': True})

        elif u.path == '/api/update_progress':
            src_path = body.get('path', '')
            status   = body.get('status', '')
            if src_path and status in ('found', 'missing', 'review'):
                _save_progress(src_path, status)
                self._json({'ok': True})
            else:
                self._json({'ok': False, 'msg': 'Invalid path or status'})

        elif u.path == '/api/clear_cache':
            file = body.get('file', '')
            try:
                if file:
                    os.remove(file)
                    msg = f'Deleted: {os.path.basename(file)}'
                else:
                    # delete all
                    deleted = 0
                    for e in list_cache_files():
                        try: os.remove(e['file']); deleted += 1
                        except Exception: pass
                    msg = f'Deleted {deleted} cache file(s).'
            except FileNotFoundError:
                msg = 'Cache file not found.'
            except Exception as ex:
                msg = str(ex)
            self._json({'ok': True, 'msg': msg})

        else:
            self._404()


# ─── Embedded UI ──────────────────────────────────────────────────────────────

_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>PhotoVerify</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">
<style>
:root {
  --bg:       #0d0f14;
  --surface:  #13161f;
  --panel:    #1a1e2a;
  --border:   #252b3b;
  --border2:  #2e3650;
  --accent:   #4f7cff;
  --red:      #ff4f6d;
  --green:    #2ecc9a;
  --yellow:   #f0b429;
  --purple:   #9b6dff;
  --text:     #dce4f0;
  --muted:    #5a6580;
  --muted2:   #7e8daa;
  --mono:     'Space Mono', monospace;
  --sans:     'DM Sans', sans-serif;
  --r:        8px;
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html, body { height: 100%; overflow: hidden; }
body {
  background: var(--bg);
  color: var(--text);
  font-family: var(--sans);
  font-size: 14px;
  display: flex;
  flex-direction: column;
}

/* ── Scrollbar ─────────────────────────────────────── */
::-webkit-scrollbar       { width: 5px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--border2); border-radius: 3px; }

/* ── Topbar ────────────────────────────────────────── */
#topbar {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 0 20px;
  height: 48px;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  flex-shrink: 0;
}
.logo {
  font-family: var(--mono);
  font-size: 14px;
  font-weight: 700;
  letter-spacing: 3px;
  text-transform: uppercase;
}
.logo em { color: var(--accent); font-style: normal; }
#topbar-spacer { flex: 1; }
.chip {
  font-family: var(--mono);
  font-size: 10px;
  padding: 3px 9px;
  border-radius: 20px;
  border: 1px solid;
  font-weight: 700;
  letter-spacing: .5px;
}
.chip-ok     { color: var(--green);  border-color: var(--green);  background: rgba(46,204,154,.1); }
.chip-warn   { color: var(--yellow); border-color: var(--yellow); background: rgba(240,180,41,.1); }
.chip-err    { color: var(--red);    border-color: var(--red);    background: rgba(255,79,109,.1); }
.chip-muted  { color: var(--muted2); border-color: var(--border2); background: transparent; }

/* ── Stats bar ─────────────────────────────────────── */
#statsbar {
  display: flex;
  align-items: center;
  gap: 0;
  padding: 0 20px;
  height: 34px;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  font-family: var(--mono);
  font-size: 11px;
  flex-shrink: 0;
}
.stat {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 0 16px;
  border-right: 1px solid var(--border);
  height: 100%;
}
.stat:first-child { padding-left: 0; }
.stat-label { color: var(--muted); }
.stat-val   { font-weight: 700; }
.stat-val.green  { color: var(--green); }
.stat-val.red    { color: var(--red); }
.stat-val.yellow { color: var(--yellow); }
.stat-val.blue   { color: var(--accent); }

/* ── Main layout ───────────────────────────────────── */
#main {
  flex: 1;
  display: flex;
  overflow: hidden;
  min-height: 0;
}

/* ── Sidebar ───────────────────────────────────────── */
#sidebar {
  width: 210px;
  flex-shrink: 0;
  display: flex;
  flex-direction: column;
  background: var(--surface);
  border-right: 1px solid var(--border);
  overflow: hidden;
}
#sidebar-head {
  display: flex;
  align-items: center;
  padding: 8px 10px;
  gap: 6px;
  border-bottom: 1px solid var(--border);
  font-size: 11px;
  color: var(--muted2);
  flex-shrink: 0;
}
#sidebar-count { font-family: var(--mono); }
#sidebar-filters {
  display: flex;
  gap: 4px;
  margin-left: auto;
}
.fbtn {
  background: transparent;
  border: 1px solid var(--border2);
  border-radius: 4px;
  color: var(--muted2);
  font-size: 10px;
  padding: 2px 6px;
  cursor: pointer;
  font-family: var(--mono);
  transition: all .15s;
}
.fbtn:hover { background: var(--panel); }
.fbtn.on { background: var(--panel); border-color: var(--accent); color: var(--accent); }

#photo-list {
  flex: 1;
  overflow-y: auto;
  overflow-x: hidden;
  position: relative;
}
#photo-list-inner {
  position: relative;
}
.pl-item {
  display: flex;
  align-items: center;
  gap: 7px;
  padding: 5px 8px;
  cursor: pointer;
  border-bottom: 1px solid rgba(37,43,59,.6);
  transition: background .1s;
  height: 54px;
  position: absolute;
  left: 0; right: 0;
}
.pl-item:hover   { background: var(--panel); }
.pl-item.current { background: var(--panel); border-left: 2px solid var(--accent); }
.pl-thumb {
  width: 40px; height: 40px;
  object-fit: cover;
  border-radius: 4px;
  background: var(--panel);
  flex-shrink: 0;
}
.pl-name {
  font-size: 11px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  flex: 1;
  min-width: 0;
}
.pl-dot {
  width: 7px; height: 7px;
  border-radius: 50%;
  flex-shrink: 0;
}
.dot-unknown { background: var(--border2); }
.dot-found   { background: var(--green); }
.dot-missing { background: var(--red); box-shadow: 0 0 4px var(--red); }
.dot-review  { background: var(--yellow); }

/* ── Viewer ─────────────────────────────────────────── */
#viewer {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  min-width: 0;
}

#panels {
  flex: 1;
  display: flex;
  overflow: hidden;
  gap: 1px;
  background: var(--border);
  min-height: 0;
}

.panel {
  flex: 1;
  display: flex;
  flex-direction: column;
  background: var(--bg);
  overflow: hidden;
  min-width: 0;
}
.panel-head {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 0 14px;
  height: 38px;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  font-size: 11px;
  font-family: var(--mono);
  color: var(--muted2);
  flex-shrink: 0;
}
.panel-head .ph-title { font-weight: 700; color: var(--muted2); text-transform: uppercase; letter-spacing: 1px; }
.panel-head .ph-name  { font-size: 10px; color: var(--muted); margin-left: auto; max-width: 280px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
#match-chip { margin-left: auto; }

.panel-body {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  overflow: hidden;
  position: relative;
  background: #08090c;
}
.panel-body img {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
  display: none;
}
.panel-body img.show { display: block; }
.ph-empty {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  color: var(--muted);
  font-size: 13px;
  text-align: center;
}
.ph-empty .icon { font-size: 36px; opacity: .3; }

/* ── Action bar ─────────────────────────────────────── */
#actionbar {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 0 16px;
  height: 54px;
  background: var(--surface);
  border-top: 1px solid var(--border);
  flex-shrink: 0;
  flex-wrap: nowrap;
  overflow: hidden;
}
.nav-btn {
  background: var(--panel);
  border: 1px solid var(--border2);
  border-radius: var(--r);
  color: var(--text);
  padding: 6px 12px;
  font-size: 12px;
  cursor: pointer;
  font-family: var(--mono);
  transition: all .15s;
  flex-shrink: 0;
}
.nav-btn:hover   { border-color: var(--accent); color: var(--accent); }
.nav-btn:disabled { opacity: .3; cursor: default; }
#nav-counter {
  font-family: var(--mono);
  font-size: 11px;
  color: var(--muted2);
  min-width: 80px;
  text-align: center;
  flex-shrink: 0;
}
#match-info {
  font-family: var(--mono);
  font-size: 10px;
  color: var(--muted);
  flex: 1;
  min-width: 0;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.action-btn {
  border: none;
  border-radius: var(--r);
  padding: 8px 14px;
  font-size: 12px;
  font-weight: 600;
  font-family: var(--sans);
  cursor: pointer;
  transition: all .15s;
  flex-shrink: 0;
  white-space: nowrap;
}
.action-btn:hover   { filter: brightness(1.15); }
.action-btn:disabled { opacity: .3; cursor: default; filter: none; }
#btn-deep    { background: var(--panel); border: 1px solid var(--purple); color: var(--purple); }
#btn-missing { background: rgba(255,79,109,.15); border: 1px solid var(--red); color: var(--red); }
#btn-review  { background: rgba(240,180,41,.12); border: 1px solid var(--yellow); color: var(--yellow); }

/* ── Setup overlay ─────────────────────────────────── */
#overlay {
  display: none;
  position: fixed; inset: 0;
  background: rgba(0,0,0,.7);
  z-index: 100;
  align-items: center;
  justify-content: center;
  backdrop-filter: blur(4px);
}
#overlay.open { display: flex; }
#modal {
  background: var(--panel);
  border: 1px solid var(--border2);
  border-radius: 12px;
  width: 540px;
  max-width: 96vw;
  max-height: 90vh;
  overflow-y: auto;
  padding: 28px;
  box-shadow: 0 24px 64px rgba(0,0,0,.6);
}
.modal-title {
  font-family: var(--mono);
  font-size: 13px;
  font-weight: 700;
  letter-spacing: 2px;
  text-transform: uppercase;
  color: var(--accent);
  margin-bottom: 22px;
}
.field { margin-bottom: 14px; }
.field label {
  display: block;
  font-size: 11px;
  font-family: var(--mono);
  color: var(--muted2);
  margin-bottom: 5px;
  text-transform: uppercase;
  letter-spacing: .5px;
}
.field input {
  width: 100%;
  background: var(--bg);
  border: 1px solid var(--border2);
  border-radius: var(--r);
  padding: 9px 12px;
  color: var(--text);
  font-size: 12px;
  font-family: var(--mono);
  outline: none;
  transition: border-color .15s;
}
.field input:focus  { border-color: var(--accent); }
.field .hint        { font-size: 10px; color: var(--muted); margin-top: 4px; }
.toggle-row {
  display: flex;
  align-items: center;
  gap: 10px;
  font-size: 13px;
  margin-bottom: 18px;
}
.toggle {
  position: relative;
  width: 38px; height: 20px;
  flex-shrink: 0;
}
.toggle input  { opacity: 0; width: 0; height: 0; position: absolute; }
.slider {
  position: absolute; inset: 0;
  background: var(--border2);
  border-radius: 20px;
  cursor: pointer;
  transition: background .2s;
}
.slider::before {
  content: '';
  position: absolute;
  width: 14px; height: 14px;
  left: 3px; top: 3px;
  background: #fff;
  border-radius: 50%;
  transition: transform .2s;
}
.toggle input:checked + .slider { background: var(--green); }
.toggle input:checked + .slider::before { transform: translateX(18px); }
#idx-box {
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--r);
  padding: 12px;
  margin-bottom: 16px;
}
#idx-msg   { font-size: 12px; color: var(--muted2); margin-bottom: 8px; font-family: var(--mono); }
#prog-bar  { height: 3px; background: var(--border); border-radius: 2px; }
#prog-fill { height: 100%; background: var(--accent); border-radius: 2px; width: 0; transition: width .3s; }
.modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  margin-top: 4px;
}
.mbtn {
  padding: 8px 16px;
  border-radius: var(--r);
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
  border: none;
  transition: filter .15s;
  font-family: var(--sans);
}
.mbtn:hover  { filter: brightness(1.1); }
.mbtn-ghost  { background: var(--bg); border: 1px solid var(--border2); color: var(--muted2); }
.mbtn-accent { background: var(--accent); color: #fff; }
.mbtn-green  { background: var(--green); color: #000; }
.mbtn-red    { background: transparent; border: 1px solid var(--red); color: var(--red); }

/* ── Log panel ─────────────────────────────────────── */
#log-overlay {
  display: none;
  position: fixed; inset: 0;
  background: rgba(0,0,0,.7);
  z-index: 100;
  align-items: center;
  justify-content: center;
  backdrop-filter: blur(4px);
}
#log-overlay.open { display: flex; }
#log-modal {
  background: var(--panel);
  border: 1px solid var(--border2);
  border-radius: 12px;
  width: 680px;
  max-width: 96vw;
  max-height: 80vh;
  display: flex;
  flex-direction: column;
  box-shadow: 0 24px 64px rgba(0,0,0,.6);
}
#log-modal-head {
  display: flex;
  align-items: center;
  padding: 16px 20px;
  border-bottom: 1px solid var(--border);
}
#log-modal-head h3 { font-family: var(--mono); font-size: 12px; letter-spacing: 2px; text-transform: uppercase; color: var(--accent); }
#log-close { margin-left: auto; background: none; border: none; color: var(--muted2); cursor: pointer; font-size: 18px; }
#log-body  { flex: 1; overflow-y: auto; padding: 12px 20px; }
.log-row   {
  display: flex; gap: 10px; align-items: center;
  padding: 8px 0;
  border-bottom: 1px solid var(--border);
  font-size: 11px;
  font-family: var(--mono);
}
.log-row .lt { color: var(--muted); flex-shrink: 0; }
.log-row .ltype { flex-shrink: 0; }
.log-row .lpath { color: var(--muted2); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

/* ── Utility ───────────────────────────────────────── */
.sep { flex: 1; }
</style>
</head>
<body>

<!-- ── Topbar ────────────────────────────────────── -->
<div id="topbar">
  <div class="logo">Photo<em>Verify</em></div>
  <div id="idx-chip" class="chip chip-muted">NOT INDEXED</div>
  <div id="topbar-spacer"></div>
  <button class="nav-btn" id="btn-scan-all" onclick="batchMatch()" disabled>Scan All</button>
  <button class="nav-btn" id="btn-save-all-missing" onclick="saveAllMissing()" disabled style="color:var(--red);border-color:var(--red)">Save All Missing</button>
  <button class="nav-btn" id="btn-save-progress" onclick="saveProgress()" disabled>Save Progress</button>
  <button class="nav-btn" onclick="openLog()">Action Log (<span id="log-count">0</span>)</button>
  <button class="nav-btn" onclick="openSetup()" style="border-color:var(--accent);color:var(--accent)">⚙ Configure</button>
</div>

<!-- ── Stats bar ─────────────────────────────────── -->
<div id="statsbar">
  <div class="stat"><span class="stat-label">TOTAL</span><span class="stat-val blue" id="st-total">0</span></div>
  <div class="stat"><span class="stat-label">CHECKED</span><span class="stat-val" id="st-checked">0</span></div>
  <div class="stat"><span class="stat-label">FOUND</span><span class="stat-val green" id="st-found">0</span></div>
  <div class="stat"><span class="stat-label">MISSING</span><span class="stat-val red" id="st-missing">0</span></div>
  <div class="stat"><span class="stat-label">REVIEW</span><span class="stat-val yellow" id="st-review">0</span></div>
</div>

<!-- ── Main ──────────────────────────────────────── -->
<div id="main">

  <!-- Sidebar -->
  <div id="sidebar">
    <div id="sidebar-head">
      <span id="sidebar-count" style="font-family:var(--mono)">0 photos</span>
      <div id="sidebar-filters">
        <button class="fbtn on" data-f="all"     onclick="setFilter('all')">ALL</button>
        <button class="fbtn"    data-f="missing" onclick="setFilter('missing')">❌</button>
        <button class="fbtn"    data-f="found"   onclick="setFilter('found')">✅</button>
      </div>
    </div>
    <div id="photo-list" onscroll="onListScroll()">
      <div id="photo-list-inner"></div>
    </div>
  </div>

  <!-- Viewer -->
  <div id="viewer">
    <div id="panels">
      <!-- Left: source -->
      <div class="panel">
        <div class="panel-head">
          <span class="ph-title">Source</span>
          <span class="ph-name" id="src-meta">—</span>
        </div>
        <div class="panel-body">
          <img id="src-img" alt="source">
          <div id="src-ph" class="ph-empty"><div class="icon">📂</div>Select a photo from the list</div>
        </div>
      </div>
      <!-- Right: dest match -->
      <div class="panel">
        <div class="panel-head">
          <span class="ph-title">Destination Match</span>
          <span id="match-chip" class="chip chip-muted">—</span>
        </div>
        <div class="panel-body">
          <img id="dest-img" alt="match">
          <div id="dest-ph" class="ph-empty"><div class="icon">🗄</div>No photo selected</div>
        </div>
      </div>
    </div>

    <!-- Action bar -->
    <div id="actionbar">
      <button class="nav-btn" id="btn-prev" onclick="navigate(-1)" disabled>◀</button>
      <span id="nav-counter">— / —</span>
      <button class="nav-btn" id="btn-next" onclick="navigate(1)"  disabled>▶</button>
      <span id="match-info"></span>
      <button class="action-btn" id="btn-deep" onclick="doDeep()" style="display:none">🔍 Hash Search</button>
      <button class="action-btn" id="btn-missing" onclick="doMove('missing')" disabled>✗ Save as Missing</button>
      <button class="action-btn" id="btn-review"  onclick="doMove('review')"  disabled>⚑ Send to Review</button>
    </div>
  </div>
</div>

<!-- ── Setup Modal ───────────────────────────────── -->
<div id="overlay" onclick="if(event.target===this)closeSetup()">
<div id="modal">
  <div class="modal-title">⚙ Configure PhotoVerify</div>

  <div class="field">
    <label>Folder 1 — Source (read-only)</label>
    <input id="cfg-src" type="text" placeholder="/path/to/source/folder" autocomplete="off">
    <div class="hint">Read-only. Never modified.</div>
  </div>
  <div class="field">
    <label>Folder 2 — Destination (read-only)</label>
    <input id="cfg-dest" type="text" placeholder="/path/to/destination/folder" autocomplete="off">
    <div class="hint">Read-only. Never modified.</div>
  </div>
  <div class="field">
    <label>Missing Output — photos confirmed not in destination go here</label>
    <input id="cfg-missing" type="text" placeholder="(defaults to photo-verify/missing)" autocomplete="off">
  </div>
  <div class="field">
    <label>Review Output — photos to manually inspect go here</label>
    <input id="cfg-review" type="text" placeholder="(defaults to photo-verify/review)" autocomplete="off">
  </div>

  <div class="toggle-row">
    <label class="toggle"><input type="checkbox" id="cfg-move"><span class="slider"></span></label>
    <span style="font-size:13px;color:var(--muted2)">
      Move files instead of copy (default is <strong style="color:var(--text)">copy</strong> — safer)
    </span>
  </div>

  <div id="idx-box">
    <div id="idx-msg">Click "Index Destination" to begin.</div>
    <div id="prog-bar"><div id="prog-fill"></div></div>
  </div>

  <div class="field" style="margin-top:4px">
    <label>Load Saved Cache</label>
    <div style="display:flex;gap:6px;align-items:center">
      <select id="cache-select" style="flex:1;background:var(--bg);border:1px solid var(--border2);border-radius:var(--r);padding:8px 10px;color:var(--text);font-size:11px;font-family:var(--mono);outline:none">
        <option value="">— none —</option>
      </select>
      <button class="mbtn mbtn-ghost" style="flex-shrink:0" onclick="refreshCacheList()">↺</button>
      <button class="mbtn mbtn-accent" style="flex-shrink:0" onclick="loadSelectedCache()">Load</button>
      <button class="mbtn mbtn-red" style="flex-shrink:0" onclick="deleteSelectedCache()">✕</button>
    </div>
    <div class="hint">Saved indexes from previous runs — one per directory scan.</div>
  </div>

  <div class="modal-footer">
    <button class="mbtn mbtn-red"   onclick="clearCache()">Clear All Caches</button>
    <button class="mbtn mbtn-ghost" onclick="startIndex()">Index Destination</button>
    <button class="mbtn mbtn-green" onclick="saveConfig()">✓ Save & Close</button>
  </div>
</div>
</div>

<!-- ── Log Modal ─────────────────────────────────── -->
<div id="log-overlay" onclick="if(event.target===this)closeLog()">
<div id="log-modal">
  <div id="log-modal-head">
    <h3>Action Log</h3>
    <button id="log-close" onclick="closeLog()">✕</button>
  </div>
  <div id="log-body"></div>
</div>
</div>

<script>
// ────────────────────────────────────────────────────────────────────────────
// App state
// ────────────────────────────────────────────────────────────────────────────
const A = {
  photos:          [],    // {i, name, path}[]  full list
  total:           0,
  currentIdx:      -1,
  statusMap:       {},    // i → 'found'|'missing'|'review'
  pathMap:         {},    // i → absolute src path
  pendingProgress: null,  // progress loaded before photos were available
  pendingIdx:      -1,    // last_idx loaded before photos were available
  filter:          'all',
  idxPoll:         null,
  _savePosTm:      null,  // debounce timer for position save
  stats: { found:0, missing:0, review:0 },
  ITEM_H: 54,             // sidebar row height px
};

// ────────────────────────────────────────────────────────────────────────────
// Bootstrap
// ────────────────────────────────────────────────────────────────────────────
async function init() {
  const s = await get('/api/state');
  window.__serverState = s;
  fill('cfg-src',     s.cfg.src);
  fill('cfg-dest',    s.cfg.dest);
  fill('cfg-missing', s.cfg.missing_dir);
  fill('cfg-review',  s.cfg.review_dir);
  document.getElementById('cfg-move').checked = s.cfg.move_mode;
  updateIdxChip(s.idx);
  refreshCacheList();
  if (s.src_count > 0) {
    await loadAllPhotos();
  }
  if (!s.pil) {
    warn('Pillow not installed. Run: pip3 install Pillow\nThumbnails and EXIF matching will not work.');
  }
}

// ────────────────────────────────────────────────────────────────────────────
// API helpers
// ────────────────────────────────────────────────────────────────────────────
async function get(url) {
  return (await fetch(url)).json();
}
async function post(url, body) {
  return (await fetch(url, {
    method: 'POST',
    headers: {'Content-Type':'application/json'},
    body: JSON.stringify(body),
  })).json();
}
function fill(id, val) {
  const el = document.getElementById(id);
  if (el && val) el.value = val;
}
function warn(msg) {
  setTimeout(() => alert(msg), 500);
}

// ────────────────────────────────────────────────────────────────────────────
// Photo list loading (paginated, all pages)
// ────────────────────────────────────────────────────────────────────────────
async function loadAllPhotos() {
  A.photos = [];
  let page = 0, pages = 1;
  while (page < pages) {
    const data = await get(`/api/list?p=${page}`);
    A.photos.push(...data.items);
    pages = data.pages;
    A.total = data.total;
    page++;
  }
  document.getElementById('sidebar-count').textContent = `${A.total} photos`;
  document.getElementById('st-total').textContent = A.total;
  document.getElementById('btn-scan-all').disabled        = false;
  document.getElementById('btn-save-all-missing').disabled = false;
  document.getElementById('btn-save-progress').disabled   = false;
  if (A.pendingProgress) {
    restoreProgress(A.pendingProgress);
    A.pendingProgress = null;
  }
  renderList();
  if (A.photos.length && A.currentIdx < 0) {
    const startAt = A.pendingIdx >= 0 ? A.pendingIdx : 0;
    A.pendingIdx = -1;
    showPhoto(startAt);
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Sidebar virtual scroll
// ────────────────────────────────────────────────────────────────────────────
function filteredPhotos() {
  if (A.filter === 'all') return A.photos;
  return A.photos.filter(p => A.statusMap[p.i] === A.filter);
}

function renderList() {
  const items   = filteredPhotos();
  const list    = document.getElementById('photo-list');
  const inner   = document.getElementById('photo-list-inner');
  const H       = A.ITEM_H;
  const total_h = items.length * H;
  const scroll  = list.scrollTop;
  const visible = list.clientHeight || 500;
  const startI  = Math.max(0, Math.floor(scroll / H) - 2);
  const endI    = Math.min(items.length, startI + Math.ceil(visible / H) + 4);

  inner.style.height = total_h + 'px';

  // Only re-render visible slice
  inner.innerHTML = items.slice(startI, endI).map((p, j) => {
    const ri = startI + j;
    const st = A.statusMap[p.i] || 'unknown';
    const cur = p.i === A.currentIdx ? 'current' : '';
    return `<div class="pl-item ${cur}" style="top:${ri*H}px"
                 onclick="showPhoto(${p.i})">
      <img class="pl-thumb" src="/thumb/src?i=${p.i}"
           onerror="this.style.background='var(--border)'">
      <span class="pl-name" title="${esc(p.name)}">${esc(p.name)}</span>
      <span class="pl-dot dot-${st}"></span>
    </div>`;
  }).join('');
}

function onListScroll() { renderList(); }

function setFilter(f) {
  A.filter = f;
  document.querySelectorAll('.fbtn').forEach(b => b.classList.toggle('on', b.dataset.f === f));
  renderList();
}

// ────────────────────────────────────────────────────────────────────────────
// Photo viewer
// ────────────────────────────────────────────────────────────────────────────
async function showPhoto(idx) {
  A.currentIdx = idx;
  clearTimeout(A._savePosTm);
  A._savePosTm = setTimeout(() => post('/api/save_position', {idx}), 800);
  const items = filteredPhotos();
  const pos   = items.findIndex(p => p.i === idx);

  // Nav counter
  document.getElementById('nav-counter').textContent = `${pos+1} / ${items.length}`;
  document.getElementById('btn-prev').disabled = pos <= 0;
  document.getElementById('btn-next').disabled = pos >= items.length - 1;
  document.getElementById('btn-missing').disabled = false;
  document.getElementById('btn-review').disabled  = false;
  document.getElementById('btn-deep').style.display = 'none';

  // Source image
  const si = document.getElementById('src-img');
  const sp = document.getElementById('src-ph');
  si.classList.remove('show');
  sp.style.display = 'flex';
  sp.innerHTML = '<div class="icon">⟳</div>Loading…';
  si.onload  = () => { si.classList.add('show'); sp.style.display='none'; };
  si.onerror = () => { sp.innerHTML='<div class="icon">⚠</div>Preview unavailable'; };
  si.src = `/thumb/src?i=${idx}&_=${Date.now()}`;

  // Metadata
  const info = await get(`/api/photo?i=${idx}`);
  document.getElementById('src-meta').textContent =
    `${info.name} · ${fmtSize(info.size)} · ${info.exif_dt}`;
  A.pathMap[idx] = info.path;

  // Match
  await resolveMatch(idx, info.path);
  renderList();
}

async function resolveMatch(idx, srcPath) {
  const chip    = document.getElementById('match-chip');
  const di      = document.getElementById('dest-img');
  const dp      = document.getElementById('dest-ph');
  const minfo   = document.getElementById('match-info');

  chip.textContent = 'CHECKING…';
  chip.className   = 'chip chip-muted';
  di.classList.remove('show');
  dp.style.display = 'flex';
  dp.innerHTML     = '<div class="icon">⟳</div>Matching…';
  minfo.textContent = '';

  const data = await get(`/api/match?i=${idx}`);
  const m    = data.match;

  if (m) {
    const labels = {filename:'FILENAME', exif:'EXIF DATE', hash:'HASH'};
    chip.textContent = `✓ ${labels[m.method]||m.method}`;
    chip.className   = 'chip chip-ok';
    minfo.textContent = `Matched via ${m.method} · ${m.n} cop${m.n>1?'ies':'y'} in destination · ${m.path.replace(/^.*?(\/\w+){3}$/, '…$&')||m.path}`;

    const enc = encodeURIComponent(m.path);
    di.onload  = () => { di.classList.add('show'); dp.style.display='none'; };
    di.onerror = () => { dp.innerHTML='<div class="icon">⚠</div>Thumbnail unavailable'; };
    di.src = `/thumb/dest?p=${enc}&_=${Date.now()}`;

    if (!A.statusMap[idx]) {
      A.statusMap[idx]='found'; A.stats.found++; updateStats();
      if (srcPath) post('/api/update_progress', {path: srcPath, status: 'found'});
    }
    document.getElementById('btn-deep').style.display = 'none';
  } else {
    chip.textContent = '✗ NOT FOUND';
    chip.className   = 'chip chip-err';
    dp.innerHTML     = '<div class="icon">❌</div>Not found in destination';
    minfo.textContent = 'No match by filename or EXIF — try hash search for certainty';
    document.getElementById('btn-deep').style.display = 'inline-block';

    if (!A.statusMap[idx]) {
      A.statusMap[idx]='missing'; A.stats.missing++; updateStats();
      if (srcPath) post('/api/update_progress', {path: srcPath, status: 'missing'});
    }
  }
  document.getElementById('st-checked').textContent = Object.keys(A.statusMap).length;
}

async function doDeep() {
  const btn = document.getElementById('btn-deep');
  btn.disabled   = true;
  btn.textContent = '⟳ Scanning…';
  const data = await get(`/api/deep_match?i=${A.currentIdx}`);
  btn.disabled   = false;
  btn.textContent = '🔍 Hash Search';
  if (data.match) {
    await resolveMatch(A.currentIdx);
  } else {
    document.getElementById('match-info').textContent =
      '✗ Confirmed missing — hash scan found no match in destination.';
    document.getElementById('match-chip').textContent = '✗ CONFIRMED MISSING';
    document.getElementById('match-chip').className   = 'chip chip-err';
  }
}

function navigate(dir) {
  const items = filteredPhotos();
  const pos   = items.findIndex(p => p.i === A.currentIdx);
  const next  = pos + dir;
  if (next >= 0 && next < items.length) showPhoto(items[next].i);
}

// ────────────────────────────────────────────────────────────────────────────
// Move/copy actions
// ────────────────────────────────────────────────────────────────────────────
async function doMove(type) {
  if (A.currentIdx < 0) return;
  const isMove = document.getElementById('cfg-move').checked;
  const label  = type === 'missing' ? 'Missing Output' : 'Review Output';
  const verb   = isMove ? 'Move' : 'Copy';
  if (!confirm(`${verb} "${filteredPhotos().find(p=>p.i===A.currentIdx)?.name}" to ${label}?`)) return;

  const r = await post('/api/move', {i: A.currentIdx, type});
  if (r.ok) {
    if (type !== 'missing') {
      A.statusMap[A.currentIdx] = 'review';
      A.stats.review++;
    }
    const srcPath = A.pathMap[A.currentIdx] || '';
    if (srcPath) post('/api/update_progress', {path: srcPath, status: type === 'missing' ? 'missing' : 'review'});
    updateStats();
    renderList();
    document.getElementById('match-info').textContent =
      `✓ ${isMove?'Moved':'Copied'} → ${r.result}`;
    document.getElementById('log-count').textContent = (parseInt(document.getElementById('log-count').textContent)||0)+1;
  } else {
    alert(`Failed to save file:\n${r.result}`);
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Bulk save missing
// ────────────────────────────────────────────────────────────────────────────
async function saveAllMissing() {
  const missing = Object.entries(A.statusMap)
    .filter(([, s]) => s === 'missing')
    .map(([i]) => parseInt(i));
  if (!missing.length) { alert('No photos marked as missing to save.'); return; }

  const verb = document.getElementById('cfg-move').checked ? 'Move' : 'Copy';
  if (!confirm(`${verb} ${missing.length} missing photo(s) to the Missing Output folder?`)) return;

  const btn = document.getElementById('btn-save-all-missing');
  btn.disabled = true;
  btn.textContent = `Saving ${missing.length}…`;

  const r = await post('/api/bulk_action', {indices: missing, type: 'missing'});
  btn.disabled = false;

  if (!r.ok && r.msg) {
    alert(`Save All Missing failed:\n${r.msg}`);
    btn.textContent = 'Save All Missing';
    return;
  }

  const folder = r.out_folder ? `\n\nFolder:\n${r.out_folder}` : '';
  const skipNote = r.skipped ? ` (${r.skipped} already saved, skipped)` : '';
  if (r.failed && r.failed.length) {
    const msgs = r.failed.slice(0, 5).map(f => `  #${f.i}: ${f.msg}`).join('\n');
    const more = r.failed.length > 5 ? `\n  …and ${r.failed.length - 5} more` : '';
    alert(`Saved ${r.saved}${skipNote}, but ${r.failed.length} failed:\n${msgs}${more}${folder}`);
  } else {
    alert(`Saved ${r.saved} file(s)${skipNote}.${folder}`);
  }

  document.getElementById('log-count').textContent =
    (parseInt(document.getElementById('log-count').textContent) || 0) + r.saved;

  btn.textContent = `Saved ${r.saved}`;
  setTimeout(() => { btn.textContent = 'Save All Missing'; }, 3000);
}

// ────────────────────────────────────────────────────────────────────────────
// Batch match
// ────────────────────────────────────────────────────────────────────────────
async function batchMatch() {
  if (!A.photos.length) { alert('Load source photos first (Save & Close in Configure).'); return; }
  const btn = document.getElementById('btn-scan-all');
  btn.disabled = true;
  btn.textContent = 'Scanning…';

  const r = await post('/api/batch_match', {force: false});
  btn.disabled = false;
  if (!r.ok) { btn.textContent = 'Scan All'; alert('Scan failed.'); return; }

  // Merge results — don't overwrite statuses already set in this session
  for (const item of r.results) {
    if (!A.statusMap[item.i]) {
      A.statusMap[item.i] = item.status;
    }
  }

  // Recount stats from full statusMap
  A.stats = {found: 0, missing: 0, review: 0};
  for (const s of Object.values(A.statusMap)) A.stats[s] = (A.stats[s] || 0) + 1;

  updateStats();
  setFilter('missing');   // show only unmatched photos for manual review

  btn.textContent = `Found ${r.found} · Missing ${r.missing}`;
  setTimeout(() => { btn.textContent = 'Scan All'; }, 3000);
}

// ────────────────────────────────────────────────────────────────────────────
// Save progress
// ────────────────────────────────────────────────────────────────────────────
async function saveProgress() {
  const btn = document.getElementById('btn-save-progress');
  btn.disabled = true;
  btn.textContent = 'Saving…';
  const r = await post('/api/save_progress_bulk', {
    idx_map:  A.statusMap,
    last_idx: A.currentIdx >= 0 ? A.currentIdx : 0,
  });
  btn.disabled = false;
  if (r.ok) {
    btn.textContent = `Saved (${r.saved})`;
    setTimeout(() => { btn.textContent = 'Save Progress'; }, 2500);
  } else {
    btn.textContent = 'Save Progress';
    alert('Save failed: ' + r.msg);
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Setup modal
// ────────────────────────────────────────────────────────────────────────────
function openSetup() {
  document.getElementById('overlay').classList.add('open');
  // Clear fields on fresh start so browser autocomplete can't ghost in old values
  const s = window.__serverState || {};
  if (!s.active_cache) {
    ['cfg-src','cfg-dest','cfg-missing','cfg-review'].forEach(id => {
      document.getElementById(id).value = '';
    });
    document.getElementById('cfg-move').checked = false;
  }
  pollIdx();
  refreshCacheList();
}
function closeSetup() {
  document.getElementById('overlay').classList.remove('open');
  if (A.idxPoll) clearInterval(A.idxPoll);
}

async function saveConfig() {
  const src     = v('cfg-src');
  const dest    = v('cfg-dest');
  const missing = v('cfg-missing');
  const review  = v('cfg-review');
  const moveMode = document.getElementById('cfg-move').checked;

  if (!src)  { alert('Source folder is required.'); return; }
  if (!dest) { alert('Destination folder is required.'); return; }
  if (!missing) { alert('Missing output folder is required.'); return; }
  if (!review)  { alert('Review output folder is required.'); return; }

  const r = await post('/api/configure', {
    cfg: {src, dest, missing_dir:missing, review_dir:review, move_mode:moveMode}
  });
  if (r.ok) {
    A.photos=[]; A.currentIdx=-1; A.statusMap={}; A.pathMap={}; A.stats={found:0,missing:0,review:0};
    document.getElementById('btn-scan-all').disabled        = true;
    document.getElementById('btn-save-all-missing').disabled = true;
    document.getElementById('btn-save-progress').disabled   = true;
    updateStats();
    await loadAllPhotos();
    closeSetup();
  } else {
    alert('Error saving config');
  }
}

async function startIndex() {
  const dest = v('cfg-dest');
  if (!dest) { alert('Set Destination folder first.'); return; }
  const r = await post('/api/start_index', {dest});
  if (!r.ok) { alert(r.msg); return; }
  pollIdx();
}

function pollIdx() {
  if (A.idxPoll) clearInterval(A.idxPoll);
  A.idxPoll = setInterval(async () => {
    const s = await get('/api/state');
    const idx = s.idx;
    document.getElementById('idx-msg').textContent  = idx.msg;
    const pct = idx.total > 0 ? (idx.current/idx.total*100) : 0;
    document.getElementById('prog-fill').style.width = pct+'%';
    updateIdxChip(idx);
    if (idx.phase === 'done' || idx.phase === 'error') clearInterval(A.idxPoll);
  }, 700);
}

async function refreshCacheList() {
  const r = await get('/api/list_caches');
  const sel = document.getElementById('cache-select');
  sel.innerHTML = '<option value="">— none —</option>';
  for (const c of r.caches) {
    const dt = new Date(c.ts * 1000).toLocaleString();
    const label = `${c.name.slice(0,15)} · ${c.n} photos · ${c.dest.split(/[\\/]/).pop() || c.dest}`;
    const opt = document.createElement('option');
    opt.value = c.file;
    opt.title = `${c.dest} — ${dt}`;
    opt.textContent = label;
    sel.appendChild(opt);
  }
}

async function loadSelectedCache() {
  const file = document.getElementById('cache-select').value;
  if (!file) { alert('Select a cache entry first.'); return; }
  const r = await post('/api/load_cache', {file});
  if (r.ok) {
    document.getElementById('idx-msg').textContent = `Loaded cache — ${r.n} photos indexed.`;
    document.getElementById('prog-fill').style.width = '100%';
    updateIdxChip({phase:'done'});
    if (r.cfg) {
      fill('cfg-src',     r.cfg.src);
      fill('cfg-dest',    r.cfg.dest);
      fill('cfg-missing', r.cfg.missing_dir);
      fill('cfg-review',  r.cfg.review_dir);
      if (r.cfg.move_mode !== undefined)
        document.getElementById('cfg-move').checked = r.cfg.move_mode;
    }
    if (r.progress && Object.keys(r.progress).length > 0) {
      if (A.photos.length > 0) restoreProgress(r.progress);
      else A.pendingProgress = r.progress;
    }
    if (r.last_idx > 0) {
      if (A.photos.length > 0) showPhoto(r.last_idx);
      else A.pendingIdx = r.last_idx;
    }
  } else {
    alert('Load failed: ' + r.msg);
  }
}

function restoreProgress(progress) {
  const pathToIdx = {};
  for (const p of A.photos) pathToIdx[p.path] = p.i;
  A.statusMap = {};
  A.stats = {found: 0, missing: 0, review: 0};
  for (const [path, status] of Object.entries(progress)) {
    const idx = pathToIdx[path];
    if (idx !== undefined) { A.statusMap[idx] = status; A.stats[status]++; }
  }
  updateStats();
  renderList();
}

async function deleteSelectedCache() {
  const file = document.getElementById('cache-select').value;
  if (!file) { alert('Select a cache entry first.'); return; }
  const name = file.split(/[\\/]/).pop();
  if (!confirm(`Delete cache file "${name}"?`)) return;
  const r = await post('/api/clear_cache', {file});
  document.getElementById('idx-msg').textContent = r.msg;
  await refreshCacheList();
}

async function clearCache() {
  if (!confirm('Delete all saved cache files?')) return;
  const r = await post('/api/clear_cache', {});
  document.getElementById('idx-msg').textContent = r.msg;
  document.getElementById('prog-fill').style.width = '0';
  await refreshCacheList();
}

function updateIdxChip(idx) {
  const c = document.getElementById('idx-chip');
  if (idx.phase === 'done') {
    c.textContent = 'INDEXED'; c.className = 'chip chip-ok';
  } else if (idx.phase === 'building' || idx.phase === 'scanning') {
    const p = idx.total>0 ? Math.round(idx.current/idx.total*100) : 0;
    c.textContent = `INDEXING ${p}%`; c.className = 'chip chip-warn';
  } else if (idx.phase === 'error') {
    c.textContent = 'INDEX ERROR'; c.className = 'chip chip-err';
  } else {
    c.textContent = 'NOT INDEXED'; c.className = 'chip chip-muted';
  }
}

// ────────────────────────────────────────────────────────────────────────────
// Log modal
// ────────────────────────────────────────────────────────────────────────────
async function openLog() {
  document.getElementById('log-overlay').classList.add('open');
  const r = await get('/api/log');
  const body = document.getElementById('log-body');
  if (!r.log.length) {
    body.innerHTML = '<div style="padding:20px;color:var(--muted);font-size:12px;">No actions yet.</div>';
    return;
  }
  body.innerHTML = [...r.log].reverse().map(l => {
    const t = new Date(l.t*1000).toLocaleTimeString();
    const cls = l.type==='missing'?'chip-err':'chip-warn';
    return `<div class="log-row">
      <span class="lt">${t}</span>
      <span class="chip ${cls}" style="font-size:9px">${l.type.toUpperCase()}</span>
      <span class="lpath" title="${esc(l.dst)}">${esc(Path_basename(l.dst))}</span>
    </div>`;
  }).join('');
}
function closeLog() { document.getElementById('log-overlay').classList.remove('open'); }

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────
function v(id)      { return document.getElementById(id)?.value?.trim() || ''; }
function esc(s)     { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
function Path_basename(p) { return p.split('/').pop() || p; }
function fmtSize(b) {
  if (b < 1024)     return b + ' B';
  if (b < 1048576)  return (b/1024).toFixed(1) + ' KB';
  return (b/1048576).toFixed(1) + ' MB';
}
function updateStats() {
  document.getElementById('st-found').textContent   = A.stats.found;
  document.getElementById('st-missing').textContent = A.stats.missing;
  document.getElementById('st-review').textContent  = A.stats.review;
  document.getElementById('st-checked').textContent = Object.keys(A.statusMap).length;
}

// ── Keyboard navigation ──────────────────────────────────────────────────────
document.addEventListener('keydown', e => {
  if (document.getElementById('overlay').classList.contains('open'))  return;
  if (document.getElementById('log-overlay').classList.contains('open')) return;
  if (e.key === 'ArrowRight' || e.key === 'ArrowDown')  navigate(1);
  if (e.key === 'ArrowLeft'  || e.key === 'ArrowUp')    navigate(-1);
  if (e.key === 'm') doMove('missing');
  if (e.key === 'r') doMove('review');
});

init();
</script>
</body>
</html>"""

# ─── Entry point ──────────────────────────────────────────────────────────────

class _QuietHTTPServer(HTTPServer):
    def handle_error(self, request, client_address):
        import traceback
        _log(f"Request from {client_address}:\n{traceback.format_exc().rstrip()}")


def main():
    print()
    print("┌─────────────────────────────────────────────┐")
    print("│   PhotoVerify — Photo Backup Checker         │")
    print("│   github: your local photo forensics tool    │")
    print("└─────────────────────────────────────────────┘")
    print()
    if not PIL_OK:
        print("  ⚠  Pillow unavailable. Install with:  pip3 install Pillow")
        print()
    print(f"  Serving at: http://localhost:{PORT}")
    print(f"  Cache dir:  {CACHE_DIR}")
    print(f"  Config dir: {CONFIG_DIR}")
    print(f"  Logs dir:   {LOGS_DIR}")
    print("  Press Ctrl+C to stop.")
    print()

    def _open():
        time.sleep(1.2)
        webbrowser.open(f"http://localhost:{PORT}")

    threading.Thread(target=_open, daemon=True).start()

    server = _QuietHTTPServer(("127.0.0.1", PORT), PhotoVerifyHandler)
    server.timeout = 0.5
    try:
        while True:
            server.handle_request()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()
        print("\n  Stopped. Goodbye.")
        sys.exit(0)

if __name__ == "__main__":
    main()
